/********************************************* Bird ********************************************/
INSERT INTO `dendrocygninaes`(`id`, `name`) 
                  VALUES (NULL,'West Indian whistling duck'),(NULL,'Wandering whistling duck'),(NULL,'Black-bellied whistling duck'),(NULL,'Fulvous whistling duck'),(NULL,'Plumed whistling duck'),(NULL,'Spotted whistling duck'),(NULL,'Lesser whistling duck'),(NULL,'White-faced whistling duck'); 

/********************************************* Bird ********************************************/
INSERT INTO `thalassorninaes`(`id`, `name`)
                  VALUES (NULL,'white-backed duck'); 


/********************************************* Bird ********************************************/
INSERT INTO `anserinaes`(`id`, `name`)
                  VALUES (NULL,'Mute swan'),(NULL,'Black swan'),(NULL,'Black-necked swan'),(NULL,'Whooper swan'),(NULL,'Trumpeter swan'),(NULL,'Tundra swan'),(NULL,'Swan goose'),(NULL,'Taiga bean goose'),(NULL,'Tundra bean goose'),(NULL,'Pink-footed goose'),(NULL,'Greater white-fronted goose'),(NULL,'Lesser white-fronted goose'),(NULL,'Greylag goose'),(NULL,'Bar-headed goose'),(NULL,'Snow goose'),(NULL,'Ross\'s goose'),(NULL,'Emperor goose'),(NULL,'Black brant'),(NULL,'Barnacle goose'),(NULL,'Pale-bellied brant goose'),(NULL,'Canada goose'),(NULL,'Cackling goose'),(NULL,'Red-breasted goose'),(NULL,'Nene or Hawaiian goose'),(NULL,'coscoroba swan'),(NULL,'Cape Barren goose'),(NULL,'New Zealand geese');

/********************************************* Bird ********************************************/
INSERT INTO `stictonettinaes`(`id`, `name`)
                  VALUES (NULL,'freckled duck');

/********************************************* Bird ********************************************/
INSERT INTO `plectropterinaes`(`id`, `name`)
                  VALUES (NULL,'spur-winged goose');

/********************************************* Bird ********************************************/
INSERT INTO `tadorninaes`(`id`, `name`)
                  VALUES (NULL,'Chatham duck'),(NULL,'Ruddy shelduck'),(NULL,'South African shelduck'),(NULL,'Australian shelduck'),(NULL,'Paradise shelduck'),(NULL,'Crested shelduck'),(NULL,'Common shelduck'),(NULL,'Raja shelduck'),(NULL,'Salvadori\'s teal'),(NULL,'Malagasy sheldgoose'),(NULL,'Malagasy shelduck'),(NULL,'Mauritius sheldgoose'),(NULL,'Reunion sheldgoose'),(NULL,'Orinoco goose'),(NULL,'Andean goose'),(NULL,'Upland goose'),(NULL,'Kelp goose'),(NULL,'Ashy-headed goose'),(NULL,'Ruddy-headed goose'),(NULL,'blue duck'),(NULL,'torrent duck'),(NULL,'pink-eared duck'),(NULL,'knob-billed duck or comb duck'),(NULL,'Flying steamer duck'),(NULL,'Fuegian steamer duck'),(NULL,'Chubut steamer duck'),(NULL,'Falkland steamer duck'),(NULL,'wood duck'),(NULL,'Mandarin duck'),(NULL,'Muscovy duck'),(NULL,'ringed teal'),(NULL,'Australian wood duck');

/********************************************* Bird ********************************************/
INSERT INTO `anatinaes`(`id`, `name`)
                  VALUES (NULL,'Baikal teal'),(NULL,'Garganey'),(NULL,'Silver teal'),(NULL,'Puna teal'),(NULL,'Hottentot teal'),(NULL,'Blue-winged teal'),(NULL,'Cinnamon teal'),(NULL,'Red shoveler'),(NULL,'Cape shoveler'),(NULL,'Australasian shoveler'),(NULL,'Northern shoveler'),(NULL,'Eurasian wigeon'),(NULL,'American wigeon'),(NULL,'Chiloe wigeon'),(NULL,'Gadwall'),(NULL,'Falcated duck'),(NULL,'Northern pintail'),(NULL,'Kerguelen Islands pintail'),(NULL,'Crozet Islands pintail'),(NULL,'South Georgia pintail'),(NULL,'Chilean pintail'),(NULL,'Niceforo\'s pintail'),(NULL,'White-cheeked pintail'),(NULL,'Red-billed teal'),(NULL,'Cape teal'),(NULL,'Bernier\'s teal'),(NULL,'Mascarene teal'),(NULL,'Sunda teal'),(NULL,'Andaman teal'),(NULL,'Grey teal'),(NULL,'Chestnut teal'),(NULL,'Eurasian teal'),(NULL,'Green-winged teal'),(NULL,'Yellow-billed teal'),(NULL,'Andean teal'),(NULL,'Auckland teal'),(NULL,'Brown teal'),(NULL,'Campbell teal'),(NULL,'African black duck'),(NULL,'Meller\'s duck'),(NULL,'Yellow-billed duck'),(NULL,'Mottled duck'),(NULL,'American black duck'),(NULL,'Mexican duck'),(NULL,'Hawaiian duck'),(NULL,'Philippine duck'),(NULL,'Laysan duck'),(NULL,'Pacific black duck'),(NULL,'Mallard'),(NULL,'Domestic duck'),(NULL,'Spot-billed duck'),(NULL,'Bronze-winged duck'),(NULL,'Crested duck'),(NULL,'Brazilian teal'),(NULL,'marbled duck or marbled teal'),(NULL,'Hartlaub\'s duck'),(NULL,'Green pygmy goose'),(NULL,'Cotton pygmy goose'),(NULL,'African pygmy goose');

/********************************************* Bird ********************************************/
INSERT INTO `aythyinaes`(`id`, `name`)
                  VALUES (NULL,'red-crested pochard'),(NULL,'rosy-billed pochard'),(NULL,'Canvasback'),(NULL,'Common pochard'),(NULL,'Redhead'),(NULL,'Ring-necked duck'),(NULL,'Hardhead'),(NULL,'Baer\'s pochard'),(NULL,'Ferruginous duck'),(NULL,'Madagascar pochard'),(NULL,'New Zealand scaup'),(NULL,'Tufted duck'),(NULL,'Greater scaup'),(NULL,'Lesser scaup');

/********************************************* Bird ********************************************/
INSERT INTO `merginaes`(`id`, `name`)
                  VALUES (NULL,'Steller\'s eider'),(NULL,'Common eider'),(NULL,'Spectacled eider'),(NULL,'King eider'),(NULL,'Harlequin duck'),(NULL,'Common scoter'),(NULL,'Black or American scoter'),(NULL,'Velvet scoter'),(NULL,'White-winged scoter'),(NULL,'Surf scoter'),(NULL,'Long-tailed duck or oldsquaw'),(NULL,'Common goldeneye'),(NULL,'Barrow\'s goldeneye'),(NULL,'Bufflehead'),(NULL,'Smew'),(NULL,'Hooded merganser'),(NULL,'Brazilian merganser'),(NULL,'Red-breasted merganser'),(NULL,'Common merganser or goosander'),(NULL,'Scaly-sided merganser');

/********************************************* Bird ********************************************/
INSERT INTO `oxyurinaes`(`id`, `name`)
                  VALUES (NULL,'black-headed duck'),(NULL,'masked duck'),(NULL,'Blue-billed duck'),(NULL,'Ruddy duck'),(NULL,'White-headed duck'),(NULL,'Maccoa duck'),(NULL,'Lake duck'),(NULL,'musk duck'),(NULL,'New Zealand musk duck');

/********************************************* Bird ********************************************/
INSERT INTO `apterygiformes`(`id`, `name`)
                  VALUES (NULL,'great spotted kiwi'),(NULL,'little spotted kiwi'),(NULL,'Okarito kiwi'),(NULL,'southern brown kiwi'),(NULL,'North Island brown kiwi');

/********************************************* Bird ********************************************/
INSERT INTO `trochilidaes`(`id`, `name`)
                  VALUES (NULL,'Allen\'s hummingbird'),(NULL,'Amazilia hummingbird'),(NULL,'Amethyst woodstar'),(NULL,'Amethyst-throated hummingbird'),(NULL,'Amethyst-throated sunangel'),(NULL,'Andean blossomcrown'),(NULL,'Andean emerald'),(NULL,'Andean hillstar'),(NULL,'Anna\'s hummingbird'),(NULL,'Antillean crested hummingbird'),(NULL,'Antillean mango'),(NULL,'Azure-crowned hummingbird'),(NULL,'Bahama woodstar'),(NULL,'Band-tailed barbthroat'),(NULL,'Bearded mountaineer'),(NULL,'Beautiful hummingbird'),(NULL,'Bee hummingbird'),(NULL,'Berylline hummingbird'),(NULL,'Black inca'),(NULL,'Black jacobin'),(NULL,'Black metaltail'),(NULL,'Black-backed thornbill'),(NULL,'Black-bellied hummingbird'),(NULL,'Black-bellied thorntail'),(NULL,'Black-billed streamertail'),(NULL,'Black-breasted hillstar'),(NULL,'Black-breasted puffleg'),(NULL,'Black-chinned hummingbird'),(NULL,'Black-crested coquette'),(NULL,'Black-eared fairy'),(NULL,'Black-hooded sunbeam'),(NULL,'Black-tailed trainbearer'),(NULL,'Black-thighed puffleg'),(NULL,'Black-throated brilliant'),(NULL,'Black-throated hermit'),(NULL,'Black-throated mango'),(NULL,'Blue-bearded helmetcrest'),(NULL,'Blue-capped hummingbird'),(NULL,'Blue-capped puffleg'),(NULL,'Blue-chested hummingbird'),(NULL,'Blue-chinned sapphire'),(NULL,'Blue-fronted lancebill'),(NULL,'Blue-headed hummingbird'),(NULL,'Blue-headed sapphire'),(NULL,'Blue-mantled thornbill'),(NULL,'Blue-tailed emerald'),(NULL,'Blue-tailed hummingbird'),(NULL,'Blue-throated goldentail'),(NULL,'Blue-throated hummingbird'),(NULL,'Blue-throated starfrontlet'),(NULL,'Blue-tufted starthroat'),(NULL,'Booted racket-tail'),(NULL,'Brazilian ruby'),(NULL,'Broad-billed hummingbird'),(NULL,'Broad-tailed hummingbird'),(NULL,'Broad-tipped hermit'),(NULL,'Bronze-tailed comet'),(NULL,'Bronze-tailed barbthroat'),(NULL,'Bronze-tailed plumeleteer'),(NULL,'Bronze-tailed thornbill'),(NULL,'Bronzy hermit'),(NULL,'Bronzy inca'),(NULL,'Brown inca'),(NULL,'Brown violetear'),(NULL,'Buff-bellied hermit'),(NULL,'Buff-bellied hummingbird'),(NULL,'Buff-breasted sabrewing'),(NULL,'Buff-tailed coronet'),(NULL,'Buff-tailed sicklebill'),(NULL,'Buff-thighed puffleg'),(NULL,'Buff-winged starfrontlet'),(NULL,'Buffy helmetcrest'),(NULL,'Buffy hummingbird'),(NULL,'Bumblebee hummingbird'),(NULL,'Calliope hummingbird'),(NULL,'Canivet\'s emerald'),(NULL,'Charming hummingbird'),(NULL,'Chestnut-bellied hummingbird'),(NULL,'Chestnut-breasted coronet'),(NULL,'Chilean woodstar'),(NULL,'Chimborazo hillstar'),(NULL,'Chiribiquete emerald'),(NULL,'Cinnamon hummingbird'),(NULL,'Cinnamon-throated hermit'),(NULL,'Collared inca'),(NULL,'Colorful puffleg'),(NULL,'Copper-rumped hummingbird'),(NULL,'Copper-tailed hummingbird'),(NULL,'Coppery emerald'),(NULL,'Coppery metaltail'),(NULL,'Coppery thorntail'),(NULL,'Coppery-bellied puffleg'),(NULL,'Coppery-headed emerald'),(NULL,'Coppery-naped puffleg'),(NULL,'Costa\'s hummingbird'),(NULL,'Cozumel emerald'),(NULL,'Crimson topaz'),(NULL,'Crowned woodnymph'),(NULL,'Cuban emerald'),(NULL,'Dot-eared coquette'),(NULL,'Dusky hummingbird'),(NULL,'Dusky-throated hermit'),(NULL,'Ecuadorian piedtail'),(NULL,'Emerald-bellied puffleg'),(NULL,'Emerald-chinned hummingbird'),(NULL,'Empress brilliant'),(NULL,'Esmeraldas woodstar'),(NULL,'Fawn-breasted brilliant'),(NULL,'Festive coquette'),(NULL,'Fiery topaz'),(NULL,'Fiery-tailed awlbill'),(NULL,'Fiery-throated hummingbird'),(NULL,'Fire-throated metaltail'),(NULL,'Fork-tailed woodnymph'),(NULL,'Frilled coquette'),(NULL,'Garden emerald'),(NULL,'Garnet-throated hummingbird'),(NULL,'Giant hummingbird'),(NULL,'Gilded sapphire'),(NULL,'Glittering-bellied emerald'),(NULL,'Glittering-throated emerald'),(NULL,'Glowing puffleg'),(NULL,'Glow-throated hummingbird'),(NULL,'Golden starfrontlet'),(NULL,'Golden-bellied starfrontlet'),(NULL,'Golden-breasted puffleg'),(NULL,'Golden-crowned emerald'),(NULL,'Golden-tailed sapphire'),(NULL,'Gorgeted puffleg'),(NULL,'Gorgeted sunangel'),(NULL,'Gorgeted woodstar'),(NULL,'Gould\'s inca'),(NULL,'Gould\'s jewelfront'),(NULL,'Gray-bellied comet'),(NULL,'Gray-breasted sabrewing'),(NULL,'Gray-chinned hermit'),(NULL,'Gray-tailed mountaingem'),(NULL,'Great sapphirewing'),(NULL,'Great-billed hermit'),(NULL,'Green hermit'),(NULL,'Green mango'),(NULL,'Green thorntail'),(NULL,'Green violetear'),(NULL,'Green-and-white hummingbird'),(NULL,'Green-backed firecrown'),(NULL,'Green-bearded helmetcrest'),(NULL,'Green-bellied hummingbird'),(NULL,'Green-breasted mango'),(NULL,'Green-breasted mountaingem'),(NULL,'Green-crowned brilliant'),(NULL,'Green-crowned plovercrest'),(NULL,'Green-fronted hummingbird'),(NULL,'Green-fronted lancebill'),(NULL,'Green-headed hillstar'),(NULL,'Greenish puffleg'),(NULL,'Green-tailed emerald'),(NULL,'Green-tailed goldenthroat'),(NULL,'Green-tailed trainbearer'),(NULL,'Green-throated carib'),(NULL,'Green-throated mango'),(NULL,'Green-throated mountaingem'),(NULL,'Hispaniolan emerald'),(NULL,'Hoary puffleg'),(NULL,'Honduran emerald'),(NULL,'Hooded visorbearer'),(NULL,'Hook-billed hermit'),(NULL,'Horned sungem'),(NULL,'Hyacinth visorbearer'),(NULL,'Inagua woodstar'),(NULL,'Indigo-capped hummingbird'),(NULL,'Jamaican mango'),(NULL,'Juan Fernandez firecrown'),(NULL,'Koepcke\'s hermit'),(NULL,'Lazuline sabrewing'),(NULL,'Little hermit'),(NULL,'Little sunangel'),(NULL,'Little woodstar'),(NULL,'Loja hummingbird'),(NULL,'Long-billed hermit'),(NULL,'Long-billed starthroat'),(NULL,'Long-tailed hermit'),(NULL,'Long-tailed sabrewing'),(NULL,'Long-tailed sylph'),(NULL,'Long-tailed woodnymph'),(NULL,'Longuemare\'s sunangel'),(NULL,'Lucifer hummingbird'),(NULL,'Magenta-throated woodstar'),(NULL,'Magnificent hummingbird'),(NULL,'Mangrove hummingbird'),(NULL,'Many-spotted hummingbird'),(NULL,'Maranhao hermit'),(NULL,'Marvellous spatuletail'),(NULL,'Mexican hermit'),(NULL,'Mexican sheartail'),(NULL,'Mexican woodnymph'),(NULL,'Minute hermit'),(NULL,'Mountain avocetbill'),(NULL,'Mountain velvetbreast'),(NULL,'Napo sabrewing'),(NULL,'Narrow-tailed emerald'),(NULL,'Neblina metaltail'),(NULL,'Needle-billed hermit'),(NULL,'Oasis hummingbird'),(NULL,'Olivaceous thornbill'),(NULL,'Olive-spotted hummingbird'),(NULL,'Orange-throated sunangel'),(NULL,'Pale-bellied hermit'),(NULL,'Pale-tailed barbthroat'),(NULL,'Peacock coquette'),(NULL,'Perija metaltail'),(NULL,'Peruvian piedtail'),(NULL,'Peruvian sheartail'),(NULL,'Pink-throated brilliant'),(NULL,'Plain-bellied emerald'),(NULL,'Plain-capped starthroat'),(NULL,'Planalto hermit'),(NULL,'Puerto Rican emerald'),(NULL,'Purple-backed sunbeam'),(NULL,'Purple-backed thornbill'),(NULL,'Purple-bibbed whitetip'),(NULL,'Purple-chested hummingbird'),(NULL,'Purple-collared woodstar'),(NULL,'Purple-crowned fairy'),(NULL,'Purple-crowned plovercrest'),(NULL,'Purple-throated carib'),(NULL,'Purple-throated mountaingem'),(NULL,'Purple-throated sunangel'),(NULL,'Purple-throated woodstar'),(NULL,'Racket-tailed coquette'),(NULL,'Rainbow starfrontlet'),(NULL,'Rainbow-bearded thornbill'),(NULL,'Red-billed streamertail'),(NULL,'Reddish hermit'),(NULL,'Red-tailed comet'),(NULL,'Rondonia emerald'),(NULL,'Royal sunangel'),(NULL,'Ruby-throated hummingbird'),(NULL,'Ruby-topaz hummingbird'),(NULL,'Rufous hummingbird'),(NULL,'Rufous sabrewing'),(NULL,'Rufous-breasted hermit'),(NULL,'Rufous-breasted sabrewing'),(NULL,'Rufous-capped thornbill'),(NULL,'Rufous-cheeked hummingbird'),(NULL,'Rufous-crested coquette'),(NULL,'Rufous-shafted woodstar'),(NULL,'Rufous-tailed hummingbird'),(NULL,'Rufous-throated sapphire'),(NULL,'Rufous-vented whitetip'),(NULL,'Rufous-webbed brilliant'),(NULL,'Santa Marta blossomcrown'),(NULL,'Santa Marta sabrewing'),(NULL,'Santa Marta woodstar'),(NULL,'Sapphire-bellied hummingbird'),(NULL,'Sapphire-spangled emerald'),(NULL,'Sapphire-throated hummingbird'),(NULL,'Sapphire-vented puffleg'),(NULL,'Saw-billed hermit'),(NULL,'Scaled metaltail'),(NULL,'Scale-throated hermit'),(NULL,'Scaly-breasted hummingbird'),(NULL,'Scintillant hummingbird'),(NULL,'Scissor-tailed hummingbird'),(NULL,'Shining sunbeam'),(NULL,'Shining-green hummingbird'),(NULL,'Short-crested coquette'),(NULL,'Short-tailed emerald'),(NULL,'Short-tailed woodstar'),(NULL,'Slender sheartail'),(NULL,'Slender-tailed woodstar'),(NULL,'Snowcap'),(NULL,'Snowy-bellied hummingbird'),(NULL,'Sombre hummingbird'),(NULL,'Sooty barbthroat'),(NULL,'Sooty-capped hermit'),(NULL,'Spangled coquette'),(NULL,'Sparkling violetear'),(NULL,'Sparkling-tailed hummingbird'),(NULL,'Speckled hummingbird'),(NULL,'Spot-throated hummingbird'),(NULL,'Steely-vented hummingbird'),(NULL,'Straight-billed hermit'),(NULL,'Streak-throated hermit'),(NULL,'Stripe-breasted starthroat'),(NULL,'Stripe-tailed hummingbird'),(NULL,'Stripe-throated hermit'),(NULL,'Swallow-tailed hummingbird'),(NULL,'Sword-billed hummingbird'),(NULL,'Tapajos hermit'),(NULL,'Tawny-bellied hermit'),(NULL,'Tepui goldenthroat'),(NULL,'Tooth-billed hummingbird'),(NULL,'Tourmaline sunangel'),(NULL,'Tufted coquette'),(NULL,'Tumbes hummingbird'),(NULL,'Turquoise-throated puffleg'),(NULL,'Tyrian metaltail'),(NULL,'Velvet-browed brilliant'),(NULL,'Velvet-purple coronet'),(NULL,'Venezuelan sylph'),(NULL,'Veraguan mango'),(NULL,'Versicolored emerald'),(NULL,'Vervain hummingbird'),(NULL,'Violet sabrewing'),(NULL,'Violet-bellied hummingbird'),(NULL,'Violet-capped hummingbird'),(NULL,'Violet-capped woodnymph'),(NULL,'Violet-chested hummingbird'),(NULL,'Violet-crowned hummingbird'),(NULL,'Violet-fronted brilliant'),(NULL,'Violet-headed hummingbird'),(NULL,'Violet-tailed sylph'),(NULL,'Violet-throated metaltail'),(NULL,'Violet-throated starfrontlet'),(NULL,'Viridian metaltail'),(NULL,'Volcano hummingbird'),(NULL,'Wedge-billed hummingbird'),(NULL,'Wedge-tailed hillstar'),(NULL,'Wedge-tailed sabrewing'),(NULL,'White-bearded helmetcrest'),(NULL,'White-bearded hermit'),(NULL,'White-bellied emerald'),(NULL,'White-bellied hummingbird'),(NULL,'White-bellied mountaingem'),(NULL,'White-bellied woodstar'),(NULL,'White-browed hermit'),(NULL,'White-chested emerald'),(NULL,'White-chinned sapphire')
,(NULL,'White-crested coquette'),(NULL,'White-eared hummingbird'),(NULL,'White-necked jacobin'),(NULL,'White-sided hillstar'),(NULL,'White-tailed emerald'),(NULL,'White-tailed goldenthroat'),(NULL,'White-tailed hillstar'),(NULL,'White-tailed hummingbird'),(NULL,'White-tailed sabrewing'),(NULL,'White-tailed starfrontlet'),(NULL,'White-throated hummingbird'),(NULL,'White-throated mountaingem'),(NULL,'White-tipped sicklebill'),(NULL,'White-tufted sunbeam'),(NULL,'White-vented plumeleteer'),(NULL,'White-vented violetear'),(NULL,'White-whiskered hermit'),(NULL,'Wine-throated hummingbird'),(NULL,'Wire-crested thorntail'),(NULL,'Xantus\'s hummingbird');
/********************************************* Bird ********************************************/
INSERT INTO `apodidaes`(`id`, `name`)
                  VALUES (NULL,'Spot-fronted swift'),(NULL,'White-chinned swift'),(NULL,'Sooty swift'),(NULL,'White-chested swift'),(NULL,'Rothschild\'s swift'),(NULL,'Great dusky swift'),(NULL,'White-fronted swift'),(NULL,'Chestnut-collared swift'),(NULL,'American black swift'),(NULL,'Biscutate swift'),(NULL,'Tepui swift'),(NULL,'White-naped swift'),(NULL,'White-collared swift'),(NULL,'Chestnut-collared swift'),(NULL,'Glossy swiftlet'),(NULL,'Cave swiftlet'),(NULL,'Pygmy swiftlet'),(NULL,'Bornean swiftlet'),(NULL,'Seychelles swiftlet'),(NULL,'Mascarene swiftlet'),(NULL,'Indian swiftlet'),(NULL,'Philippine swiftlet'),(NULL,'Halmahera swiftlet'),(NULL,'Sulawesi swiftlet'),(NULL,'Seram swiftlet'),(NULL,'Mountain swiftlet'),(NULL,'White-rumped swiftlet'),(NULL,'Australian swiftlet'),(NULL,'Himalayan swiftlet'),(NULL,'Indochinese swiftlet'),(NULL,'Volcano swiftlet'),(NULL,'Whitehead\'s swiftlet'),(NULL,'Bare-legged swiftlet'),(NULL,'Mayr\'s swiftlet'),(NULL,'Palawan swiftlet'),(NULL,'Mossy-nest swiftlet'),(NULL,'Uniform swiftlet'),(NULL,'Palau swiftlet'),(NULL,'Mariana swiftlet'),(NULL,'Island swiftlet'),(NULL,'Atiu swiftlet'),(NULL,'Tahiti swiftlet'),(NULL,'Marquesan swiftlet'),(NULL,'Black-nest swiftlet'),(NULL,'Edible-nest swiftlet'),(NULL,'Germain\'s swiftlet'),(NULL,'Three-toed swiftlet'),(NULL,'Giant swiftlet'),(NULL,'Scarce swift'),(NULL,'Schouteden\'s swift'),(NULL,'Philippine spine-tailed swift'),(NULL,'Papuan spine-tailed swift'),(NULL,'Madagascar spinetail'),(NULL,'Sao Tome spinetail'),(NULL,'White-rumped spinetail'),(NULL,'Black spinetail'),(NULL,'Mottled spinetail'),(NULL,'Silver-rumped spinetail'),(NULL,'Sabine\'s spinetail'),(NULL,'Bohm\'s spinetail'),(NULL,'Cassin\'s spinetail'),(NULL,'White-throated needletail'),(NULL,'Purple needletail'),(NULL,'Silver-backed needletail'),(NULL,'Brown-backed needletail'),(NULL,'Band-rumped swift'),(NULL,'Lesser Antillean swift'),(NULL,'Gray-rumped swift'),(NULL,'Pale-rumped swift'),(NULL,'Chimney swift'),(NULL,'Vaux\'s swift'),(NULL,'Chapman\'s swift'),(NULL,'Short-tailed swift'),(NULL,'Ashy-tailed swift'),(NULL,'Sick\'s swift'),(NULL,'Amazonian swift'),(NULL,'Costa Rican swift'),(NULL,'White-throated swift'),(NULL,'White-tipped swift'),(NULL,'Andean swift'),(NULL,'Pygmy palm swift'),(NULL,'Neotropical palm swift'),(NULL,'Antillean palm swift'),(NULL,'Great swallow-tailed swift'),(NULL,'Lesser swallow-tailed swift'),(NULL,'Asian palm swift'),(NULL,'African palm swift'),(NULL,'Alpine swift'),(NULL,'Mottled swift'),(NULL,'Cape Verde swift'),(NULL,'Common swift'),(NULL,'Plain swift'),(NULL,'Nyanza swift'),(NULL,'Pallid swift'),(NULL,'African black swift'),(NULL,'Forbes-Watson\'s swift'),(NULL,'Bradfield\'s swift'),(NULL,'Malagasy black swift'),(NULL,'Pacific swift'),(NULL,'Salim Ali\'s swift'),(NULL,'Blyth\'s swift'),(NULL,'Cook\'s swift'),(NULL,'Dark-rumped swift'),(NULL,'Little swift'),(NULL,'House swift'),(NULL,'Horus swift'),(NULL,'White-rumped swift'),(NULL,'Bates\' swift'),(NULL,'Fernando Po swift');



/********************************************* Bird ********************************************/
INSERT INTO `hemiprocnidaes`(`id`, `name`)
                  VALUES (NULL,'Crested treeswift'),(NULL,'Grey-rumped treeswift'),(NULL,'Whiskered treeswift'),(NULL,'Moustached treeswift');


/********************************************* Bird ********************************************/
INSERT INTO `casuariiformes`(`id`, `name`)
                  VALUES (NULL,'double-wattled cassowary'),(NULL,'Dwarf cassowary'),(NULL,'single-wattled cassowary'),(NULL,'emu');



/********************************************* Bird ********************************************/
INSERT INTO `scolopacis`(`id`, `name`)
                  VALUES (NULL,'Whimbrel'),(NULL,'Eurasian curlew'),(NULL,'Long-billed curlew'),(NULL,'Far Eastern curlew'),(NULL,'Little curlew'),(NULL,'Bristle-thighed curlew'),(NULL,'upland sandpiper'),(NULL,'Black-tailed godwit'),(NULL,'Hudsonian godwit'),(NULL,'Bar-tailed godwit'),(NULL,'Marbled godwit'),(NULL,'Short-billed dowitcher'),(NULL,'Long-billed dowitcher'),(NULL,'Asiatic dowitcher'),(NULL,'Eurasian woodcock'),(NULL,'Amami woodcock'),(NULL,'Javan woodcock'),(NULL,'New Guinea woodcock'),(NULL,'Bukidnon woodcock'),(NULL,'Sulawesi woodcock'),(NULL,'Moluccan woodcock'),(NULL,'American woodcock'),(NULL,'Snipe'),(NULL,'red phalarope'),(NULL,'red-necked phalarope'),(NULL,'Wilson\'s phalarope'),(NULL,'Green sandpiper'),(NULL,'Solitary sandpiper'),(NULL,'Grey-tailed tattler'),(NULL,'Wandering tattler'),(NULL,'Spotted redshank'),(NULL,'Greater yellowlegs'),(NULL,'Common greenshank'),(NULL,'Willet'),(NULL,'Lesser yellowlegs'),(NULL,'Nordmann\'s greenshank'),(NULL,'Marsh sandpiper'),(NULL,'Common redshank'),(NULL,'Wood sandpiper'),(NULL,'Grey-tailed tattler'),(NULL,'Wandering tattler'),(NULL,'Tuamotu sandpiper'),(NULL,'Surfbird'),(NULL,'Great knot'),(NULL,'Red knot'),(NULL,'Sanderling'),(NULL,'Semipalmated sandpiper'),(NULL,'Western sandpiper'),(NULL,'Red-necked stint'),(NULL,'Little stint'),(NULL,'Temminck\'s stint'),(NULL,'Long-toed stint'),(NULL,'Least sandpiper'),(NULL,'White-rumped sandpiper'),(NULL,'Baird\'s sandpiper'),(NULL,'Pectoral sandpiper'),(NULL,'Sharp-tailed sandpiper'),(NULL,'Curlew sandpiper'),(NULL,'Purple sandpiper'),(NULL,'Rock sandpiper'),(NULL,'Dunlin'),(NULL,'Stilt sandpiper'),(NULL,'Spoon-billed sandpiper'),(NULL,'Broad-billed sandpiper'),(NULL,'Buff-breasted sandpiper'),(NULL,'Ruff'),(NULL,'ruddy turnstone'),(NULL,'black turnstone');


/********************************************* Bird https://en.wikipedia.org/wiki/Painted-snipe ********************************************/
INSERT INTO `thinocoris`(`id`, `name`)
                  VALUES (NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,'');


/********************************************* Bird ********************************************/
INSERT INTO `s`(`id`, `name`)
                  VALUES (NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,''),(NULL,'');














































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































